exports.PORT = process.env.PORT || '8081';
exports.SCOPE_PRESETS = {
    presets: [
        {
            _id: "123",
            label: "Power Control",
            channels: [
                {label: "Channel 1", value: "Actual Setpoint"},
                {label: "Channel 2", value: "Forward Power"},
                {label: "Channel 3", value: "Reserve Power"},
                {label: "Channel 4", value: "Gamma Real"},
                {label: "Channel 5", value: "Gamma Imag"},
                {label: "Channel 6", value: "Pulse State"},
                {label: "Channel 7", value: "PA Drive Setpoint"},
                {label: "Channel 8", value: "Frequency"},
                {label: "Channel 9", value: "Rail Setpoint"},
                {label: "Channel 10", value: "Disabled"},
                {label: "Channel 11", value: "Disabled"},
                {label: "Channel 12", value: "Disabled"},
                {label: "Channel 13", value: "Disabled"},
                {label: "Channel 14", value: "Disabled"},
                {label: "Channel 15", value: "Disabled"},
                {label: "Channel 16", value: "Disabled"}
            ],
            description: [
                {label: "Samples Per Second", value: 10003},
                {label: "Number of Data Points", value: 233016},
                {label: "Pretrigger %", value: 99},
                {label: "Trigger Holdoff (ms)", value: 0},
                {label: "Channel 1", value: "Actual Setpoint"},
                {label: "Channel 2", value: "Forward Power"},
                {label: "Channel 3", value: "Reserve Power"},
                {label: "Channel 4", value: "Gamma Real"},
                {label: "Channel 5", value: "Gamma Imag"},
                {label: "Channel 6", value: "Pulse State"},
                {label: "Channel 7", value: "PA Drive Setpoint"},
                {label: "Channel 8", value: "Frequency"},
                {label: "Channel 9", value: "Rail Setpoint"},
                {label: "Channel 10", value: "Disabled"},
                {label: "Channel 11", value: "Disabled"},
                {label: "Channel 12", value: "Disabled"},
                {label: "Channel 13", value: "Disabled"},
                {label: "Channel 14", value: "Disabled"},
                {label: "Channel 15", value: "Disabled"},
                {label: "Channel 16", value: "Disabled"}
            ]},
        {
            _id: "234",
            label: "High Speed Power Control",
            description: [
                {label: "Samples Per Second", value: 139508},
                {label: "Number of Data Points", value: 262144},
                {label: "Pretrigger %", value: 99},
                {label: "Trigger Holdoff (ms)", value: 0},
                {label: "Channel 1", value: "Actual Setpoint"},
                {label: "Channel 2", value: "Forward Power"},
                {label: "Channel 3", value: "Reserve Power"},
                {label: "Channel 4", value: "Gamma Real"},
                {label: "Channel 5", value: "Gamma Imag"},
                {label: "Channel 6", value: "Pulse State"},
                {label: "Channel 7", value: "PA Drive Setpoint"},
                {label: "Channel 8", value: "Frequency"},
                {label: "Channel 9", value: "Rail Setpoint"},
                {label: "Channel 10", value: "V ADC"},
                {label: "Channel 11", value: "I ADC"},
                {label: "Channel 12", value: "ADC Index"},
                {label: "Channel 13", value: "PID Out"},
                {label: "Channel 14", value: "APT Out"},
                {label: "Channel 15", value: "ADC Bin"},
                {label: "Channel 16", value: "PRBS Power"}
            ]
        },
        {
            _id: "345",
            label: "Ultra Fast Power Control",
            description: [
                {label: "Samples Per Second", value: 10003},
                {label: "Number of Data Points", value: 2097152},
                {label: "Pretrigger %", value: 99},
                {label: "Trigger Holdoff (ms)", value: 0},
                {label: "Channel 1", value: "Disabled"},
                {label: "Channel 2", value: "Disabled"},
                {label: "Channel 3", value: "Disabled"},
                {label: "Channel 4", value: "Disabled"},
                {label: "Channel 5", value: "Disabled"},
                {label: "Channel 6", value: "Disabled"},
                {label: "Channel 7", value: "Disabled"},
                {label: "Channel 8", value: "Disabled"},
                {label: "Channel 9", value: "Disabled"},
                {label: "Channel 10", value: "Disabled"},
                {label: "Channel 11", value: "Disabled"},
                {label: "Channel 12", value: "Disabled"},
                {label: "Channel 13", value: "Disabled"},
                {label: "Channel 14", value: "Disabled"},
                {label: "Channel 15", value: "Disabled"},
                {label: "Channel 16", value: "Disabled"}
            ]
        },
        {
            _id: "456",
            label: "Frequency Tuning",
            description: [
                {label: "Samples Per Second", value: 10003},
                {label: "Number of Data Points", value: 2097152},
                {label: "Pretrigger %", value: 99},
                {label: "Trigger Holdoff (ms)", value: 0},
                {label: "Channel 1", value: "State 1 Frequency"},
                {label: "Channel 2", value: "Frequency Mode"},
                {label: "Channel 3", value: "Distortion Real"},
                {label: "Channel 4", value: "Distortion Imag"},
                {label: "Channel 5", value: "State 2 Frequency"},
                {label: "Channel 6", value: "State 3 Frequency"},
                {label: "Channel 7", value: "State 4 Frequency"},
                {label: "Channel 8", value: "C1 Position"},
                {label: "Channel 9", value: "Disabled"},
                {label: "Channel 10", value: "Disabled"},
                {label: "Channel 11", value: "Disabled"},
                {label: "Channel 12", value: "Disabled"},
                {label: "Channel 13", value: "Disabled"},
                {label: "Channel 14", value: "Disabled"},
                {label: "Channel 15", value: "Disabled"},
                {label: "Channel 16", value: "Disabled"}
            ]},
        {
            _id: "567",
            label: "Metering",
            description: [
                {label: "Samples Per Second", value: 10003},
                {label: "Number of Data Points", value: 233016},
                {label: "Pretrigger %", value: 99},
                {label: "Trigger Holdoff (ms)", value: 0},
                {label: "Channel 1", value: "PSU 1 Fan Amps"},
                {label: "Channel 2", value: "PSU 1 Mode"},
                {label: "Channel 3", value: "PA01 Current"},
                {label: "Channel 4", value: "PA Voltage"},
                {label: "Channel 5", value: "PSU 1 Temp"},
                {label: "Channel 6", value: "Soft Start Volts"},
                {label: "Channel 7", value: "Ambient Air Temp"},
                {label: "Channel 8", value: "HK Bias Voltage"},
                {label: "Channel 9", value: "Total PA Current"},
                {label: "Channel 10", value: "Disabled"},
                {label: "Channel 11", value: "Disabled"},
                {label: "Channel 12", value: "Disabled"},
                {label: "Channel 13", value: "Disabled"},
                {label: "Channel 14", value: "Disabled"},
                {label: "Channel 15", value: "Disabled"},
                {label: "Channel 16", value: "Disabled"}
            ]},
        {
            _id: "678",
            label: "Power Feedback",
            description: [
                {label: "Samples Per Second", value: -1},
                {label: "Number of Data Points", value: -1},
                {label: "Pretrigger %", value: 99},
                {label: "Trigger Holdoff (ms)", value: 0},
                {label: "Channel 1", value: "VFwd Real"},
                {label: "Channel 2", value: "VFwd Imag"},
                {label: "Channel 3", value: "IRvs Real"},
                {label: "Channel 4", value: "IRvs Imag"},
                {label: "Channel 5", value: "TDM MUX Sel"},
                {label: "Channel 6", value: "Disabled"},
                {label: "Channel 7", value: "Disabled"},
                {label: "Channel 8", value: "Disabled"},
                {label: "Channel 9", value: "Disabled"},
                {label: "Channel 10", value: "Disabled"},
                {label: "Channel 11", value: "Disabled"},
                {label: "Channel 12", value: "Disabled"},
                {label: "Channel 13", value: "Disabled"},
                {label: "Channel 14", value: "Disabled"},
                {label: "Channel 15", value: "Disabled"},
                {label: "Channel 16", value: "Disabled"}
            ]},
        {
            _id: "789",
            label: "Pulsing",
            description: [
                {label: "Samples Per Second", value: 10003},
                {label: "Number of Data Points", value: 161319},
                {label: "Pretrigger %", value: 99},
                {label: "Trigger Holdoff (ms)", value: 0},
                {label: "Channel 1", value: "Actual Setpoint"},
                {label: "Channel 2", value: "Forward Power"},
                {label: "Channel 3", value: "Reverse Power"},
                {label: "Channel 4", value: "Gamma Real"},
                {label: "Channel 5", value: "Gamma Imag"},
                {label: "Channel 6", value: "Pulse State"},
                {label: "Channel 7", value: "PA Drive Setpoint"},
                {label: "Channel 8", value: "Period"},
                {label: "Channel 9", value: "Duty Factor"},
                {label: "Channel 10", value: "Sync Period"},
                {label: "Channel 11", value: "Sync Duty Factor"},
                {label: "Channel 12", value: "Sync Valid"},
                {label: "Channel 13", value: "Pulsing Status Vector"},
                {label: "Channel 14", value: "Disabled"},
                {label: "Channel 15", value: "Disabled"},
                {label: "Channel 16", value: "Disabled"}
            ]},
        {
            _id: "890",
            label: "Fault",
            description: [
                {label: "Samples Per Second", value: 10003},
                {label: "Number of Data Points", value: 174762},
                {label: "Pretrigger %", value: 99},
                {label: "Trigger Holdoff (ms)", value: 0},
                {label: "Channel 1", value: "Actual Setpoint"},
                {label: "Channel 2", value: "Forward Power"},
                {label: "Channel 3", value: "Reverse Power"},
                {label: "Channel 4", value: "Gamma Real"},
                {label: "Channel 5", value: "Gamma Imag"},
                {label: "Channel 6", value: "Pulse State"},
                {label: "Channel 7", value: "PA Drive Setpoint"},
                {label: "Channel 8", value: "Frequency"},
                {label: "Channel 9", value: "TLC Code"},
                {label: "Channel 10", value: "PA Voltage"},
                {label: "Channel 11", value: "PA Power Dissipation"},
                {label: "Channel 12", value: "Status Vector"},
                {label: "Channel 13", value: "Disabled"},
                {label: "Channel 14", value: "Disabled"},
                {label: "Channel 15", value: "Disabled"},
                {label: "Channel 16", value: "Disabled"}
            ]}
    ]
}
